### ISSUE TITLE
V-dompurify - HTML automatically removes target=" blank"

### ISSUE THREAD

**Issue by latiaoJW** [LeSuisse/vue-dompurify-html#1258]
`<a target="_blank">test</a>`   =>   `<a>test</a>`
I want to keep target=" blank"

**Comment by LeSuisse** [comment]
Hello,

This is the expected behavior of DOMPurify, you can override it with a hook see https://github.com/cure53/DOMPurify/issues/317 for more information.

You can setup DOMPurify hooks when adding vue-dompurify-html to your app;
```js
app.use(VueDOMPurifyHTML, {
  hooks: {
    afterSanitizeAttributes: (currentNode) => {
      // Do something with the node
    }   
  }
});
```
