### ISSUE TITLE
Example: How to remove ALL HTML elements and tags from an input?

### ISSUE THREAD

**Issue by dosstx** [LeSuisse/vue-dompurify-html#1425]
Ok stupid question.....but how to remove ALL html from an input and just leave the basic text?

For example:

`<b>Hello World</b>` should be `Hello World`.

I tried:

 ```
Vue.use(VueDOMPurifyHTML, {
  USE_PROFILES: {
    html: false
  }
})
```

But <span v-dompurify-html="formValues.caption"></span> Still showed the `b` element in the user input.

**Comment by LeSuisse** [comment]
Closing since this was not directly related to `vue-dompurify-html`.
