### ISSUE TITLE
Update dompurify to the latest version

### ISSUE THREAD

**Issue by KosKosovuch** [LeSuisse/vue-dompurify-html#1548]
[Versions](https://www.npmjs.com/package/dompurify) - dompurify

`"dependencies": {
    "dompurify": "^2.0.0"
  },`

**Comment by LeSuisse** [comment]
Hello,

What's the issue here?

The latest version of DOMPurify is 2.3.4 which is covered by the range ^2.0.0.

**Comment by KosKosovuch** [comment]
Hello! 

[Fixed the problem with `target="_blank"` attr](https://github.com/nhn/tui.calendar/pull/915)

**Comment by LeSuisse** [comment]
You can already pull the latest version of DOMPurify, the range specified by `vue-dompurify-html` already allows it.. If you use `npm`, running `npm update dompurify` should do the trick. If you are not using the latest version of `npm` you might need to also specify the `--depth` option, see [RFC00019](https://github.com/npm/rfcs/blob/main/implemented/0019-remove-update-depth-option.md) for more information.

However note that even the latest version of DOMPurify remove the `target="_blank"` attribute so you will still have to use a hook.

**Comment by LeSuisse** [comment]
I'm going to close this one. It is not directly related to `vue-dompurify-html`.

Anyway a 2.4.0 and 3.0.0-beta.1 of `vue-dompurify-html` have been released and they both set DOMPurify 2.3.4 as the minimal supported version.

**Comment by LeSuisse** [comment]
Also see #1258
