### ISSUE TITLE
Cannot be implemented in vue3

### ISSUE THREAD

**Issue by liao666brant** [LeSuisse/vue-dompurify-html#1697]
// in vue file
```
<template>
  <div v-dompurify-html="data"></div>
</template>
```

// in main.ts
```
import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import VueDOMPurifyHTML from 'vue-dompurify-html';
const app = createApp(App, {
  data: () => ({
    rawHtml: '<span style="color: red">This should be red.</span>',
  }),
});
app.use(VueDOMPurifyHTML);
app.use(router);
app.mount('#app');
```

In this case, the v-dompurify-html cannot take effect

**Comment by LeSuisse** [comment]
Hello,

I'm not sure what I'm missing here, I checked the small example available in the repo and it seems to work fine on my end https://github.com/LeSuisse/vue-dompurify-html/blob/vue-next/example/example.ts


Would you mind setting up a reproduction repository on Stackblitz https://stackblitz.com/fork/vue or somewhere else (here on GitHub is fine too)?

**Comment by liao666brant** [comment]
> Hello,
> 
> I'm not sure what I'm missing here, I checked the small example available in the repo and it seems to work fine on my end https://github.com/LeSuisse/vue-dompurify-html/blob/vue-next/example/example.ts
> 
> Would you mind setting up a reproduction repository on Stackblitz https://stackblitz.com/fork/vue or somewhere else (here on GitHub is fine too)?

Thank your help, it`s very useful.
In addition, I think you need to update the help document.
The current help documents are so outdated and vague that they are misleading.


Here is the code after success
```
import { createApp } from 'vue';
import App from './App.vue';
import router from './router';
import VueDOMPurifyHTML from 'vue-dompurify-html';

const app = createApp(App);

app.use(VueDOMPurifyHTML, {
  namedConfigurations: {
    plaintext: {
      USE_PROFILES: { html: false },
    },
  },
});
app.use(router);
app.mount('#app');
```

**Comment by LeSuisse** [comment]
What information is outdated in this README https://github.com/LeSuisse/vue-dompurify-html/tree/vue-next? Would you mind opening a PR?

The only absolutely needed thing is to load the plugin and use a directive. It is a pretty standard thing in the Vue ecosystem.

**Comment by liao666brant** [comment]
> What information is outdated in this README https://github.com/LeSuisse/vue-dompurify-html/tree/vue-next? Would you mind opening a PR?
> 
> The only absolutely needed thing is to load the plugin and use a directive. It is a pretty standard thing in the Vue ecosystem.

OK, I'll do it as soon as possible opening a PR

**Comment by liao666brant** [comment]
```
import { createApp } from 'vue'
import VueDOMPurifyHTML from 'vue-dompurify-html'

const app = createApp({
    data: () => ({
        rawHtml: '<span style="color: red">This should be red.</span>'
    })
});
app.use(VueDOMPurifyHTML);
app.mount('#app');
```

```
import { createApp } from 'vue';
import App from './App.vue';
import VueDOMPurifyHTML from 'vue-dompurify-html';

const app = createApp(App);

app.use(VueDOMPurifyHTML, {
  namedConfigurations: {
    plaintext: {
      USE_PROFILES: { html: false },
    },
  },
});
app.mount('#app');
```

There are some differences between the two configurations.
The first method cannot be used normally.
The second method can be used normally, but I don't know how to be compatible with the custom attributes of the first method.

But this approach is ineffective
```
const app = createApp(App, {
  data: () => ({
    rawHtml: '<span style="color: red">This should be red.</span>',
  }),
});
```

Is this custom attribute necessary?
```
    data: () => ({
        rawHtml: '<span style="color: red">This should be red.</span>',
        svgContent: '<svg><rect height="50"></rect></svg>'
    })
```

**Comment by LeSuisse** [comment]
Thanks for the PR, I understand better what the issue is now!

I rewrote the README using SFC and `<script setup>`, does it look better?

**Comment by liao666brant** [comment]
It better.

**Comment by LeSuisse** [comment]
Thanks for the feedback.
