### ISSUE TITLE
Purify :href

### ISSUE THREAD

**Issue by mat1cl** [LeSuisse/vue-dompurify-html#1747]
Hello, currently I found myself making a project using VUE 2.x, the sources are analyzed by SonarQ Cloud, which told me that using "v-html" was dangerous, so it started using "v-dompurify-html", which I fixed the problem, but now it tells me that using “:href” is also dangerous. Tried with “v-dompurify-html:href” but it doesn't seem to work :(

Is there a method inside “vue-dompurify-html” that allows purifying the “:href”?

Greetings.

**Comment by LeSuisse** [comment]
Hello,

No, DOMPurify processes HTML as a whole so there is no dedicated part for HREFs. If you want to bind untrusted href maybe process the value with something like [@braintree/sanitize-url](https://github.com/braintree/sanitize-url) or take a look at the regex used by DOMPurify: https://github.com/cure53/DOMPurify/blob/2.3.6/src/regexp.js#L8-L10

**Comment by mat1cl** [comment]
Thank you very much “**LeSuisse**” for the clarification.

Just in case it helps anyone, I was able to fix the SonarQ Cloud issue using “@braintree/sanitize-url”.

Example:

<a :href=”sanitizeUrl(‘www.fakeurl.com’)”></a>

Greetings.
