### ISSUE TITLE
Purified Content Somehow Duplicated to Sibling Element

### ISSUE THREAD

**Issue by lostncg** [LeSuisse/vue-dompurify-html#1791]
Reproducible Demo:
https://codesandbox.io/s/cool-moon-3hdvjh?file=/src/App.vue

When the element is injected with v-dompurify-html, if its both siblings (before && after) are dynamic rendered (eg: v-if), somehow the purified content will be duplicated to its sibling element above.

**Comment by LeSuisse** [comment]
Hello,

Thanks for the bug report with a reproduction scenario. I will check what's going on.

**Comment by LeSuisse** [comment]
Fixed in 2.5.2.
