### ISSUE TITLE
dompurify-html and vue-test-utils

### ISSUE THREAD

**Issue by OmelyanenkoV** [LeSuisse/vue-dompurify-html#2450]
Hi, when trying to register VueDOMPurifyHTML in shallowMount/mount. I am getting an error saying wrapper is undefined.
![image](https://user-images.githubusercontent.com/47278133/221926858-9f6c755f-7633-4503-bdef-e27a68e9809a.png)
`TypeError: Cannot read properties of undefined (reading 'unmount')`

I also tried to register the directive without registering the plugin.
![image](https://user-images.githubusercontent.com/47278133/221927185-97bcf95c-fa2c-4691-8e06-510734f5b157.png)
In this case, the tests are launched. But the component I need - does not render content.

Approximately so looks usage in a component.
`<span v-dompurify-html="t('footer.terms', [LANDING_URL, locale])" />
 <span v-dompurify-html="t('footer.privacy', [LANDING_URL, locale])" />`

I may be making a mistake during the plugin registration process, or this error may not be related to the plugin, but a test utils problem. But if you can suggest something - I will be grateful.

**Comment by LeSuisse** [comment]
Hello,

Do you have a minimal reproduction repository where I could see the repository?

From what I see from the screenshots the usage seems fine but without seeing the whole thing it is hard to be helpful.

https://antfu.me/posts/why-reproductions-are-required
