### ISSUE TITLE
Upgraded to 4.1.4 got issue

### ISSUE THREAD

**Issue by hanscahya** [LeSuisse/vue-dompurify-html#2706]
I just upgrade to version 4.1.4 and got this issue

```
Module parse failed: Unexpected token (4:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

| import { isVue3 as m } from "vue-demi";
| function p(o, i) {
>   const n = o.hooks ?? {};
|   let t;
|   for (t in n) {
```

I've been looking for a solution but didn't find anything useful.

Not sure if this related, but I'm using nuxt (^2.15.8)

**Comment by LeSuisse** [comment]
Hello,

It appears that your setup does not support the `??` operator. I suggest that you make you make adjustments to your bundler/build toolchain config to rewrite them. See also #2386.
