### ISSUE TITLE
It can't support Nuxt3

### ISSUE THREAD

**Issue by freezyh** [LeSuisse/vue-dompurify-html#2829]
I use last version 5.0.0, I don't know how to config in Nuxt3 defineNuxtPlugin

**Comment by LeSuisse** [comment]
I added an example, see https://github.com/LeSuisse/vue-dompurify-html/tree/main/packages/vue-dompurify-html#usage-with-nuxt-3

For server side rendering see the discussion in #1917

**Comment by gspgsp** [comment]
i also use "nuxt": "^3.13.2",  this : https://github.com/LeSuisse/vue-dompurify-html/tree/main/packages/vue-dompurify-html#usage-with-nuxt-3 is useful
