### ISSUE TITLE
Search robots doesn't see innerHTML content in nuxt

### ISSUE THREAD

**Issue by coldestheart** [LeSuisse/vue-dompurify-html#360]
Hello, i've tried to use dompurify in my nuxt ssr project, but when i getting data via api search robot doesn't see innerHTML, tag only. When i replace dompurify with v-html, all works good, There is anyway to solve this?

**Comment by LeSuisse** [comment]
Hi,

I'm not really familiar with SSR, however DOMPurify itself supports running on node 12 and with JSDOM.

Would you be able to provide a minimal test scenario for the issue?

**Comment by LeSuisse** [comment]
I took a quick look and it seems it would require a custom implementation if you process the content server side (see nuxt/nuxt.js#898) so I'm guessing that as is `vue-dompurify-html`  does not work with nuxt.

If someone which to contribute something I would be glad to accept a PR.
